name: Update RKE2 References
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: 'targetted RKE2 version'
        required: true
        options:
          - "v1.33.13"
          - "v1.33.1"
          - "v1.33.2"
          - "v1.34.9"
          - "v1.35.6"
          - "v1.36.2"

jobs:
  update-references:
    name: "Update RKE2 References"
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout `ecm-config.json`"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          sparse-checkout: |
            ecm-config.json

      - name: "Setup `ecm-distro-tools` CLI"
        uses: rancher/ecm-distro-tools@016551c414f82e64af8c4c18315ea3093d10be7c # v0.74.3

      - name: "Open `rancher/rke2` PR Updating `{{ inputs.version }}` References"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          VERSION: ${{ inputs.version }}
        run: release update rke2 references ${VERSION} --config-file=ecm-config.json
